import pyodbc
import pandas as pd

# conexão com seu DSN (igual da imagem)
conn = pyodbc.connect(
    "DSN=Teraprod;UID=BRWAA1;PWD=Henri@2024"
)

query = """
SELECT
    D.CALENDARDAYDT,
    MNLOCCD,
    PrchDivDesc,
    CAST(SUM(SALEAMT) AS INT) AS VL_TOTAL
FROM BR_PRD_VIEW.RTL_FT_SALE_TICKET_DIL DA 
INNER JOIN BR_PRD_VIEW.RTL_DM_LOCATION LO ON (DA.LOCID = LO.LOCID)
INNER JOIN BR_PRD_VIEW.RTL_DM_ITEM IT ON (IT.ITEMIDSK = DA.ITEMIDSK)
LEFT JOIN BR_PRD_VIEW.RTL_DAY D ON (DA.CALDAYDT = D.CALENDARDAYDT)
LEFT JOIN BR_PRD_VIEW.RTL_CEA_WEEK W ON (D.CEAWEEKID = W.CEAWEEKID)
WHERE D.CEAWEEKID BETWEEN '202401' AND '202552'
AND DA.LOCID = 695
GROUP BY D.CALENDARDAYDT, MNLOCCD, PrchDivDesc
ORDER BY D.CALENDARDAYDT
"""

df = pd.read_sql(query, conn)

print(df.head())
print(df.shape)